#!/bin/sh
sqlplus64 "d1yeung/06145080@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

-- Drop tables if they exist, with cascade constraints
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Customer_Phone CASCADE CONSTRAINTS;
DROP TABLE Customer_Email CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE Equipment CASCADE CONSTRAINTS;
DROP TABLE Equipment_Type CASCADE CONSTRAINTS;
DROP TABLE Rental CASCADE CONSTRAINTS;
DROP TABLE Rental_History CASCADE CONSTRAINTS;
DROP TABLE Overdue CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Payment_History CASCADE CONSTRAINTS;
DROP TABLE Reservation CASCADE CONSTRAINTS;
DROP TABLE Maintenance CASCADE CONSTRAINTS;

EOF
